# Generated by Django 4.2.11 on 2024-09-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='a', max_length=12)),
                ('dinero', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=False)),
                ('descripcion', models.TextField(default='', null=True)),
            ],
        ),
    ]
