# Generated by Django 4.2.11 on 2024-09-27 08:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0002_usuario_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='a', max_length=10)),
                ('puntuacion', models.FloatField(default=0.4)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.usuario')),
            ],
        ),
    ]
